server:
  port: 8102

spring:
  application:
    name: orion-api-gateway
  # todo 切换配置文件
  profiles:
    active: prod
  cloud:
    gateway:
      routes:
        - id: path_route
          uri: http://localhost:8103
          predicates:
            - Path=/**
  redis:
    host: ${orion.redis.host}
    port: ${orion.redis.port}
    database: ${orion.redis.database}
#    password: ${orion.redis.password}
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace
dubbo:
  application:
    name: ${orion.dubbo.application.name}
  protocol:
    name: ${orion.dubbo.protocol.name}
    port: ${orion.dubbo.protocol.port}
  registry:
    id: ${orion.dubbo.registry.id}
    address: ${orion.dubbo.registry.address}

